version: "3.8"
services:
  app:
    build:
    container_name: node_app
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - PORT=${PORT}
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
volumes: mongo_data
